# =========================
# Dockerfile.dev — Dành cho môi trường phát triển
# =========================
# Dùng Node 22 giống môi trường ngoài
FROM node:22
# Tạo thư mục làm việc
WORKDIR /app

# Copy file cấu hình trước
COPY package*.json ./

# Cài dependencies
RUN npm install

# Copy toàn bộ source code
COPY . .

# Thiết lập biến môi trường
# ENV NODE_ENV=development
ENV PORT=11112

# Mở port
EXPOSE 11112

# Chạy Next.js ở chế độ dev (tự reload khi code thay đổi)
CMD ["npm", "run", "dev"]
